# Generated by Django 5.2.6 on 2025-10-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_text', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.employee')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.trainingmodule')),
            ],
        ),
        migrations.CreateModel(
            name='TestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.IntegerField(default=30)),
                ('passing_percentage', models.FloatField(default=70.0)),
                ('retrain_days', models.IntegerField(default=365)),
                ('enforce_retrain', models.BooleanField(default=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_config', to='chatbot.trainingmodule')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.URLField(blank=True, max_length=500, null=True)),
                ('choice_a', models.TextField()),
                ('choice_b', models.TextField()),
                ('choice_c', models.TextField()),
                ('choice_d', models.TextField()),
                ('correct_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('weight', models.FloatField(default=1.0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='chatbot.trainingmodule')),
            ],
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.mcq')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='chatbot.testattempt')),
            ],
            options={
                'indexes': [models.Index(fields=['attempt'], name='chatbot_tes_attempt_c9043f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.employee')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.trainingmodule')),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'module', 'completed_at'], name='chatbot_tes_user_id_cd40e2_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['module'], name='chatbot_mcq_module__fee299_idx'),
        ),
    ]
